[package]
name = "secure_sign_rust"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
libc = "0.2.80"
jni = "0.17.0"

[build-dependencies]
cbindgen = "0.28.0"
